# Simple package
# collect some kaimoji from https://slangit.com/emoticons/kaomoji

name: kaimoji
parent: default

matches:
  - trigger: ":sniper:"
    replace: "( ´-ω･)︻┻┳══━一"
  - trigger: ":disapproval:"
    replace: "ಠ_ಠ"
  - trigger: ":distraught:"
    replace: "༼ ༎ຶ ෴ ༎ຶ༽"
  - trigger: ":doing_homework:"
    replace: "＿φ( °-°)/"
  - trigger: ":shrugging:"
    replace: "¯\_(ツ)_/¯"
  - trigger: ":ghost:"
    replace: "(((༼•̫͡•༽)))"
  - trigger: ":doggy:"
    replace: "V●ᴥ●V"
  - trigger: ":crazy:"
    replace: "(◐‿◑)﻿"
  - trigger: ":dog:"
    replace: "◤◡ᴥ◡◥ "
  - trigger: ":outlaw:"
    replace: "̿’̿’\\̵͇̿̿\\З=( ͠° ͟ʖ ͡°)=Ε/̵͇̿̿/’̿̿ ̿ ̿ ̿ ̿ ̿"
  - trigger: ":wizard:"
    replace: "(∩｀-´)⊃━☆ﾟ.*･｡ﾟ"
  - trigger: ":feisty:"
    replace: "(ง •̀_•́)ง"
  - trigger: ":but_at_what_cost:"
    replace: "ლ(ಠ益ಠლ)"
  - trigger: ":take_my_energy:"
    replace: "༼ つ ◕_◕ ༽つ"
  - trigger: ":dancing:"
    replace: "♪┏(・o･)┛♪"
  - trigger: ":butterfly:"
    replace: "Ƹ̵̡Ӝ̵̨̄Ʒ"
  - trigger: ":thumbs_up:"
    replace: "d-(^.^)z"
  - trigger: ":flipping_table:"
    replace: "(╯°□°）╯︵ ┻━┻"
  - trigger: ":kirby:"
    replace: "(っ^‿^)っ"
  - trigger: ":deal_with_it:"
    replace: "(▀̿Ĺ̯▀̿ ̿)"
  - trigger: ":annoyed:"
    replace: "(¬_¬\")"
  - trigger: ":crying:"
    replace: "T^T"
  - trigger: ":polar_bear:"
    replace: "ʕ•͡ᴥ•ʔ"
  - trigger: ":snowing:"
    replace: "❆❅❉"
  - trigger: ":koala:"
    replace: "ʕ •ᴥ•ʔ"
  - trigger: ":kitty_cat:"
    replace: "⋟^≏^⋞"
  - trigger: ":joyful:"
    replace: "(≧∇≦)/"
  - trigger: ":stereo:"
    replace: "|̲̅̅●̲̅̅|̲̅̅=̲̅̅|̲̅̅●̲̅̅|"
  - trigger: ":sword_fighting:"
    replace: "(´>_●)メ(●_<｀)"
  - trigger: ":worried:"
    replace: "(´╹〽╹`)"
  - trigger: ":sad:"
    replace: "T.T"
  - trigger: ":table_flips_you:"
    replace: "┬─┬﻿︵/(.□.)╯"
  - trigger: ":kyubey:"
    replace: "／人◕ ‿‿ ◕人＼"
  - trigger: ":smiling:"
    replace: "( ͡° ͜ʖ ͡°)"
  - trigger: ":hug_me:"
    replace: "⊂((・▽・))⊃"
  - trigger: ":bowling:"
    replace: "＝( ^o^)ノ___ｏ"
  - trigger: ":cat:"
    replace: "(=◑ᆺ◐=)"
  - trigger: ":herp_derp:"
    replace: "（。々°）"
  - trigger: ":puppy:"
    replace: "U＾ェ＾U"
  - trigger: ":frosty_the_snowman:"
    replace: "ᒄ₍⁽ˆ⁰ˆ⁾₎ᒃ♪♬"
  - trigger: ":confused:"
    replace: "¯\\(°_o)/¯"
  - trigger: ":gimme:"
    replace: "༼ つ ◕_◕ ༽つ"
  - trigger: ":squid:"
    replace: "<コ:彡"
  - trigger: ":loving:"
    replace: "(ɔ◔‿◔)ɔ ♥"
  - trigger: ":overjoyed:"
    replace: "^_^"
  - trigger: ":in_love:"
    replace: "(♥_♥)"
  - trigger: ":happy:"
    replace: "（●＾o＾●）"
  - trigger: ":painful:"
    replace: "(>_<)"
  - trigger: ":spongebob_squarepants:"
    replace: "|∴め ϖ め∴|"
  - trigger: ":seal:"
    replace: "(ᵔᴥᵔ)"
  - trigger: ":zombie:"
    replace: "[¬º-°]¬"
  - trigger: ":pig:"
    replace: "<(^oo^)>"
  - trigger: ":furious:"
    replace: "(ò_ó)"
  - trigger: ":monocle:"
    replace: "ಠ_ರೃ"
  - trigger: ":sobbing:"
    replace: "(ू˃̣̣̣̣̣̣︿˂̣̣̣̣̣̣ ू)"
  - trigger: ":whoops:"
    replace: "(－‸ლ)"
  - trigger: ":giving_up:"
    replace: "(;-_-)ノ"
  - trigger: ":yoo-hoo:"
    replace: "(ﾉﾟ0ﾟ)ﾉ~"
  - trigger: ":buddies:"
    replace: "(*^o^)人(^o^*)"
  - trigger: ":celebrating:"
    replace: "ᕕ( ᐛ )ᕗ"
  - trigger: ":mustache:"
    replace: "( ￣┏＿┓￣)"
  - trigger: ":flexing:"
    replace: "ᕦ(ò_óˇ)ᕤ"
  - trigger: ":nyan_cat:"
    replace: "•.,¸,.•*`•.,¸¸,.•*¯ ╭━━━━╮"
  - trigger: ":laughing:"
    replace: "(＾▽＾)"
  - trigger: ":hippie:"
    replace: "(✿◠‿◠) "
  - trigger: ":peace:"
    replace: "(^o^)y"
  - trigger: ":emo:"
    replace: "(//_^)"
  - trigger: ":anime_sweat_drop:"
    replace: "-_-;"
  - trigger: ":running:"
    replace: "ε=┏( >_<)┛"
  - trigger: ":guilty:"
    replace: "^_^;"
  - trigger: ":excited:"
    replace: "ヽ(★ω★)ノ"
  - trigger: ":scared:"
    replace: ".∵･(ﾟДﾟ)"
  - trigger: ":staring:"
    replace: "(;￢_￢)"
  - trigger: ":shocked:"
    replace: "⊙▂⊙"
  - trigger: ":teddy_bear:"
    replace: "⊂(^(工)^)⊃"
  - trigger: ":flipping_facebook:"
    replace: "(╯°□°)╯︵ ʞooqǝɔɐɟ"
  - trigger: ":fish:"
    replace: "ϵ( 'Θ' )϶"
  - trigger: ":high_five:"
    replace: "^_^/"
  - trigger: ":magic_attack:"
    replace: "(∩｀-´)⊃━☆ﾟ.*･｡ﾟ"
  - trigger: ":superhero:"
    replace: "─=≡Σ(([ ⊐•̀⌂•́]⊐"
  - trigger: ":huh:"
    replace: "[•.•ิ]"
  - trigger: ":snooper:"
    replace: "┬┴┬┴┤(･_├┬┴┬┴"
  - trigger: ":walrus:"
    replace: "(:3 っ)っ"
  - trigger: ":reluctant:"
    replace: "o(´^｀)o"
  - trigger: ":bear:"
    replace: "⊂(￣(ｴ)￣)⊃"
  - trigger: ":shy:"
    replace: "（/｡＼)"
  - trigger: ":unimpressed:"
    replace: "（￣～￣）"
  - trigger: ":panda:"
    replace: "◖㈠ ω ㈠◗"
  - trigger: ":sleeping_kirby:"
    replace: "૮(-.-)ა"
  - trigger: ":angry:"
    replace: "ヽ(｀⌒´メ)ノ"
  - trigger: ":pumped:"
    replace: "o(^▽^)o"
  - trigger: ":anger:"
    replace: "ლ(ಠ益ಠ)ლ"
  - trigger: ":punching:"
    replace: "(o￣∇￣)=◯)`ν゜)･"
  - trigger: ":sleeping:"
    replace: "(–˛ — º)"
  - trigger: ":frustrated:"
    replace: "-_-*"
  - trigger: ":devastated:"
    replace: "(ಥ﹏ಥ)"
  - trigger: ":octopus:"
    replace: "Ｃ:。ミ"
  - trigger: ":sleepy:"
    replace: "(- o - ) zzZ ☽"
  - trigger: ":bird:"
    replace: "(●∈∋●)"
  - trigger: ":darth_vader:"
    replace: "(｡▼皿▼)"
  - trigger: ":hug:"
    replace: "(っ⌒‿⌒)っ"
  - trigger: ":gleeful:"
    replace: "｡◕‿◕｡"
  - trigger: ":whatever:"
    replace: "¬.¬"
  - trigger: ":bat:"
    replace: "/|\\( ;,; )/|\\"
  - trigger: ":playing_in_the_snow:"
    replace: "◦°˚\\☺/˚°◦"
  - trigger: ":dj:"
    replace: "d^_^b"
  - trigger: ":imbecile:"
    replace: "(＊☉౪ ⊙｡)ﾉ"
  - trigger: ":pumped_up:"
    replace: "ヽ( ★ω★)ノ"
  - trigger: ":happy_crying:"
    replace: "(°̥̥̥̥̥̥̥̥ᴗ°̥̥̥̥̥̥̥̥)"
  - trigger: ":clown:"
    replace: "⫷ °⧭° ⫸"
  - trigger: ":arm_wrestle:"
    replace: "( `_)乂(_' )"
  - trigger: ":gift:"
    replace: "(´・ω・)っ由"
  - trigger: ":beaten_up:"
    replace: "(*@_＊#)"
  - trigger: ":content:"
    replace: "˙ ͜ʟ˙"
  - trigger: ":hiding:"
    replace: "|д･)"
  - trigger: ":muscular_person:"
    replace: "ᕦ❍ᴗ❍ᕤ"
  - trigger: ":oh_no!:"
    replace: "L(´□｀L)"
  - trigger: ":scaring:"
    replace: "(☄ฺ◣д◢)☄ฺ"
  - trigger: ":playstation_portable:"
    replace: "(+[__]∙:∙)"
  - trigger: ":bunny:"
    replace: "(=^_^=)"
  - trigger: ":skeptical:"
    replace: "(•͡.•͡)"
  - trigger: ":rolling_eyes:"
    replace: "◔̯◔"
  - trigger: ":freak_out:"
    replace: "ヽ(ﾟДﾟ)ﾉ"
  - trigger: ":anticipation:"
    replace: "(⊃‿⊂)"
  - trigger: ":psycho:"
    replace: "ヘ（。□°）ヘ"
  - trigger: ":snubbing:"
    replace: "(´･ω･`)"
  - trigger: ":syringe:"
    replace: "-{'''|'''|'''|''']=[]"
  - trigger: ":weary:"
    replace: "(´~`)"
  - trigger: ":unamused:"
    replace: "(ㆆ_ㆆ)"
  - trigger: ":inquisitive:"
    replace: "(╭ರ_•́)"
  - trigger: ":cyclops:"
    replace: "๏-)"
  - trigger: ":thinking:"
    replace: "(p_-)"
  - trigger: ":glad:"
    replace: "＼（＾ ＾）／"
  - trigger: ":waving:"
    replace: "( ^_^)／"
  - trigger: ":best_buds:"
    replace: "（　＾＾）人（＾＾　）"
  - trigger: ":surrender:"
    replace: "(ﾉ_ _)ﾉ"
  - trigger: ":lethargic:"
    replace: "(‾ʖ̫‾)"
  - trigger: ":fu_manchu_man:"
    replace: "(￣┏∞┓￣)"
  - trigger: ":tired:"
    replace: "〠_〠"
  - trigger: ":pikachu:"
    replace: "(o^-^o)"
  - trigger: ":table_tennis:"
    replace: "‎(>o<)ρミ┳┷┳゜"
  - trigger: ":on_the_phone:"
    replace: "(〃＾∇＾)】"
  - trigger: ":kitty:"
    replace: "(=^･ｪ･^=)"
  - trigger: ":disgruntled:"
    replace: "( ͡° ʖ̯ ͡°)"
  - trigger: ":dreaming:"
    replace: "(_ _)..ooOO"
  - trigger: ":chameleon:"
    replace: "ᘛ⁐̤ᕐᐷ"
  - trigger: ":surprised:"
    replace: "（￣□￣；）"
  - trigger: ":kiss_me:"
    replace: "( ˘ ³˘)♥"
  - trigger: ":dead_person:"
    replace: "✖‿✖"
  - trigger: ":shooting:"
    replace: "(ﾟ皿ﾟ)ｒ┏┳－*"
  - trigger: ":boogie_down:"
    replace: "ヽ(⌐■_■)ノ♪♬"
  - trigger: ":bear_cub:"
    replace: "(ó㉨ò)"
  - trigger: ":rabbit:"
    replace: "U=･ x ･=U"
  - trigger: ":olympic_hammer_throw:"
    replace: "(ﾉ-o-)ﾉ 中"
  - trigger: ":infatuated:"
    replace: "（*´▽｀*）"
  - trigger: ":fighting:"
    replace: "(ง •̀ゝ•́)ง"
  - trigger: ":puzzled:"
    replace: "「(°ヘ°)"
  - trigger: ":cunning:"
    replace: "(¬‿¬)"
  - trigger: ":embarrassed:"
    replace: "(#^.^#)"
  - trigger: ":putting_table_back:"
    replace: "┬─┬ノ( º _ ºノ)"
  - trigger: ":yikes:"
    replace: "(☉__☉”)"
  - trigger: ":skipping:"
    replace: "ε=┌(^-^)┘"
  - trigger: ":chasing_a_butterfly:"
    replace: "〜〜(／￣▽)／　〜ф"
  - trigger: ":good_morning:"
    replace: "＼（～Ｏ～）／"
  - trigger: ":evading:"
    replace: "((((((^_^;)"
  - trigger: ":pigtails:"
    replace: "∋∞(●ﾟvﾟ)∞∈"
  - trigger: ":frantic:"
    replace: "(ﾟДﾟ≡ﾟДﾟ)"
  - trigger: ":hitting:"
    replace: "( ｀皿´)｡ﾐ/"
  - trigger: ":weeping:"
    replace: "｡･ﾟﾟ･(>д<)･ﾟﾟ･｡"
  - trigger: ":confused_shrug:"
    replace: "¯(°_o)/¯"
  - trigger: ":magic_casting:"
    replace: "（*・)｢｣｢｣"
  - trigger: ":ashamed:"
    replace: "(；一_一)"
  - trigger: ":writing:"
    replace: "＿〆(。。)"
  - trigger: ":dead:"
    replace: "(#×_×)"
  - trigger: ":whistling:"
    replace: "♪～(￣ε￣；)"
  - trigger: ":wait:"
    replace: "(″･ิ_･ิ)っ"
  - trigger: ":crab:"
    replace: "V=(° °)=V"
  - trigger: ":bow_and_arrow:"
    replace: "<( ･ｪ-)<}"
  - trigger: ":elton_john:"
    replace: "⪿ ↂ ˒̫̮ ↂ ⫀"
  - trigger: ":good_night:"
    replace: "♪(●′▽`)ﾉ"
  - trigger: ":worshiping:"
    replace: "ƪ(˘▽˘ƪ)"
  - trigger: ":demon:"
    replace: "^(#｀∀´)_Ψ"
  - trigger: ":zoidberg:"
    replace: "(V) (°,,,,°) (V)"
  - trigger: ":whispering:"
    replace: "( ￣ﾉ∇￣)￣ｰ￣)"
  - trigger: ":painting:"
    replace: "(。･_･)ノ”【】"
  - trigger: ":deceased:"
    replace: "(✖╭╮✖)"
  - trigger: ":phone:"
    replace: "(((☎)))"
  - trigger: ":happy_anime_face:"
    replace: "uwu"
  - trigger: ":rocking_out:"
    replace: "\\m/d(^_^)b\\m/"
  - trigger: ":slapping:"
    replace: "(；^＿^)ッ☆(　゜o゜)"
  - trigger: ":shifty:"
    replace: "(¬､¬)"
  - trigger: ":putting_facebook_back_after_flipping_it:"
    replace: "Facebookノ( º _ ºノ)"
  - trigger: ":eager:"
    replace: "ʘ‿ʘ"
  - trigger: ":proposal:"
    replace: "( ° ᴗ°)~ð "
  - trigger: ":lifting_weights:"
    replace: "¤\\( `⌂´ )/¤"
  - trigger: ":singing:"
    replace: "(^o^)"
  - trigger: ":playing_ping_pong:"
    replace: "( •_•)O °Q(•_• )"
  - trigger: ":bro_pound:"
    replace: "(ó ì_í)=óò=(ì_í ò)"
  - trigger: ":neglected:"
    replace: "(¬_¬ )"
  - trigger: ":kicking:"
    replace: "( ｀o´)_θ☆"
  - trigger: ":yummy:"
    replace: "(っ˘ڡ˘ς)"
  - trigger: ":scheming:"
    replace: "ಠᴗಠ"
  - trigger: ":loving_couple:"
    replace: "(ɔˆ ³(ˆ⌣ˆc)"
  - trigger: ":smitten:"
    replace: "(｡♥‿♥｡)"
  - trigger: ":romantic:"
    replace: "(ɔ˘з˘)ɔ"
  - trigger: ":smoking:"
    replace: "y(^ o^)y~~"
  - trigger: ":thank_you:"
    replace: "＼(-_- )"
  - trigger: ":caroling:"
    replace: "＼(^o)(^0^)(o^)／"
  - trigger: ":hugging:"
    replace: "(>^_^)><(^o^<)"
  - trigger: ":victory:"
    replace: "v(^_^)v"
  - trigger: ":pucker_up:"
    replace: "（*＾3＾）"
  - trigger: ":celebrate:"
    replace: "＼(＾O＾)／"
  - trigger: ":best_buddies:"
    replace: "└(^o^ )Ｘ( ^o^)┘"
  - trigger: ":praying:"
    replace: "(╯˘ -˘ )╯"
  - trigger: ":winnie_the_pooh:"
    replace: "ʕ •́؈•̀)"
  - trigger: ":groggy:"
    replace: "(-_ゞ"
  - trigger: ":robot:"
    replace: "¥[*.*]¥"
  - trigger: ":pointing:"
    replace: "（￢з￢）σ"
  - trigger: ":blowing_a_kiss:"
    replace: "(-□-)︵*"
  - trigger: ":bawling:"
    replace: "ಥ_ಥ"
  - trigger: ":golf_clap:"
    replace: "(´ー｀)┌ﾌｯ"
  - trigger: ":laser:"
    replace: "m( ﾟ皿ﾟ)m★━━"
  - trigger: ":upset:"
    replace: ">.<"
  - trigger: ":john_lennon:"
    replace: "⎰≀.☮-☮≀⎰"
  - trigger: ":ringo_starr:"
    replace: "✌(გ_㇁გ)✌"
  - trigger: ":precious:"
    replace: "（人’∀’）"
  - trigger: ":cold:"
    replace: "╹﹏╹"
  - trigger: ":how_should_i_know:"
    replace: "┗(･ω･;)┛"
  - trigger: ":put_em_up:"
    replace: "Q('.'Q)"
  - trigger: ":suspicious:"
    replace: "⊂ •͡˘∠•͡˘ ⊃"
  - trigger: ":attentive:"
    replace: "(⌒ ͜ʖ⌒)b"
  - trigger: ":smile:"
    replace: "(ʘ‿ʘ)"
  - trigger: ":blushing:"
    replace: "(๑´•.̫ • `๑)"
  - trigger: ":bad_hair_day:"
    replace: "༼ঢ_㇁ঢ༽"
  - trigger: ":depressed:"
    replace: "( ◢д◣)"
  - trigger: ":satisfied:"
    replace: "(▰˘◡˘▰)"
  - trigger: ":poodle:"
    replace: "੯ू‵ू ໒꒱"
  - trigger: ":winking:"
    replace: "(^‿◕)"
  - trigger: ":big_grin:"
    replace: "(￣▼￣)"
  - trigger: ":kitten:"
    replace: "-ˆ ω ˆ-"
  - trigger: ":fed_up:"
    replace: "＼(｀0´)／"
  - trigger: ":chubby:"
    replace: "^)_(^"
  - trigger: ":help:"
    replace: "(o´・Υ・)ﾉ･"
  - trigger: ":teasing:"
    replace: ":-Þ"
  - trigger: ":jealous:"
    replace: "8(>_<)8"
  - trigger: ":goodbye:"
    replace: "(^ _ ^)/~~"
  - trigger: ":listening_to_music:"
    replace: "d(^_^)b"
  - trigger: ":giggling:"
    replace: "(о＾ω＾о)"
  - trigger: ":kissing:"
    replace: "(* ￣)(￣ *) "
  - trigger: ":mellow:"
    replace: "ヽ（´ー｀）┌"
  - trigger: ":accidental_farting:"
    replace: "ε=(☉_☉)"
  - trigger: ":ninja_star:"
    replace: "( --)/ ==卍"
  - trigger: ":eye_roll_with_hands_up:"
    replace: "٩◔̯◔۶"
  - trigger: ":scary:"
    replace: "(╯‵Д′)╯"
  - trigger: ":header:"
    replace: "(( ＿ ＿)☆ ≡〇"
  - trigger: ":exorcism:"
    replace: "†_(ﾟｰﾟ*)β"
  - trigger: ":larry_david:"
    replace: "㐈⦁ཽし⦁ཽ㐈 "
  - trigger: ":lobster:"
    replace: "☉ϖ☉"
  - trigger: ":puppy_love:"
    replace: "∊♡_ᴥ_♡∍"
  - trigger: ":cheerful:"
    replace: "(＾▽＾)"
  - trigger: ":teleporting:"
    replace: "(((((^_^)"
  - trigger: ":perplexed:"
    replace: "༼ঢ_༽ঢ༽"
  - trigger: ":ping_pong_table:"
    replace: "┳┻┳°"
  - trigger: ":livid:"
    replace: "(*｀へ´*)"
  - trigger: ":aang:"
    replace: "O(<>'<>)O"
  - trigger: ":chasing:"
    replace: "(○｀д´)ﾉｼ Σ(っﾟДﾟ)っ"
  - trigger: ":vampire:"
    replace: "(*▿▿* ƪ)"
  - trigger: ":smooch:"
    replace: "(づ￣ ³￣)づ"
  - trigger: ":wink:"
    replace: "(`_^)"
  - trigger: ":porcupine:"
    replace: "(•ᴥ• )́`́'́`́'́⻍"
  - trigger: ":hopeful:"
    replace: "o(^^o)(o^^)o"
  - trigger: ":geek:"
    replace: "◖⎚∠⎚◗"
  - trigger: ":enamored:"
    replace: "♥‿♥"
  - trigger: ":sprinting:"
    replace: "ε=ε=ε=┌(๑ʘ∀ʘ)┘"
  - trigger: ":licking:"
    replace: "ლ(´ڡ`ლ)"
  - trigger: ":tripping:"
    replace: "｡｡｡(o_ _)o⌒☆"
  - trigger: ":poking:"
    replace: "(*・)σσ(*゜O゜)"
  - trigger: ":nagato:"
    replace: "•:_:•"
  - trigger: ":grandma:"
    replace: "◖ර◞ʖ◟ර◗"
  - trigger: ":peering:"
    replace: "(/ω･＼)"
  - trigger: ":scissor_kick:"
    replace: "/( ＿0＿)￣θ☆≡≡○"
  - trigger: ":blissful:"
    replace: "^^"
  - trigger: ":nodding:"
    replace: "(￣ー￣（＿　＿（"
  - trigger: ":volleyball:"
    replace: "(／o^)/°⊥＼(^o＼)"
  - trigger: ":beefcake:"
    replace: "└@(･ｪ･)@┐"
  - trigger: ":looking:"
    replace: "←(･_･┐)"
  - trigger: ":elated:"
    replace: "ε=┌( ≧▽)┘"
  - trigger: ":bathtub:"
    replace: "\\＿(´▽｀)♪＿/"
  - trigger: ":mog:"
    replace: "^o^"
  - trigger: ":discontent:"
    replace: "（￣へ￣）"
  - trigger: ":falling_asleep:"
    replace: "(+.+)(-.-)(_ _)"
  - trigger: ":pie_fight:"
    replace: "(~_(]=--Z(◡˘)"
  - trigger: ":hiding_easter_eggs:"
    replace: "( • ∀•)っθΘʘ"
  - trigger: ":blowfish:"
    replace: "∋(°O°)∈"
  - trigger: ":comforting:"
    replace: "(。。;)＼(-_-)"
  - trigger: ":hipster:"
    replace: "( ˇ෴ˇ )"
  - trigger: ":heartbroken:"
    replace: "(∿°○°)∿ ︵ ǝʌol"
  - trigger: ":yelling:"
    replace: "ヾ(*￣O￣)ツ"
  - trigger: ":panicking:"
    replace: "\\(<.<|>.>)//"
  - trigger: ":hurt:"
    replace: "┗( ●-﹏ ｀｡)づ"
  - trigger: ":kiss_my_butt:"
    replace: "（＿ε＿）"
  - trigger: ":drinking:"
    replace: "( -_-)旦~"
  - trigger: ":satan:"
    replace: "←～（o ｀▽´ )oΨ"
  - trigger: ":grooving:"
    replace: "└(^o^)┐"
  - trigger: ":crazed:"
    replace: "(⊙_◎)"
  - trigger: ":pleased:"
    replace: "(─‿‿─)"
  - trigger: ":raving:"
    replace: "～゜・_・゜～"
  - trigger: ":bread:"
    replace: "ʕʔ"
  - trigger: ":sonic_the_hedgehog:"
    replace: "੯ू•́ू ໒꒱⁼³₌₃"
  - trigger: ":throwing_away:"
    replace: "(*・_・)ノ⌒*"
  - trigger: ":distressed:"
    replace: "∊ಠ_ಠ∍"
  - trigger: ":punched:"
    replace: "(。_°)☆"
  - trigger: ":benjamin_franklin:"
    replace: "⨌⨀_⨀⨌"
  - trigger: ":spider:"
    replace: "^;;^"
  - trigger: ":cyborg:"
    replace: "(╬☉Д⊙ฺ)"
  - trigger: ":enraged:"
    replace: "˃ʍ˂"
  - trigger: ":cutting_a_rug:"
    replace: "┌|°з°|┘"
  - trigger: ":meh:"
    replace: "（＾～＾）"
  - trigger: ":boxer:"
    replace: "o(^_-)O"
  - trigger: ":punch:"
    replace: "（。_°☆＼(- – )"
  - trigger: ":ninja:"
    replace: "[-_-]~"
  - trigger: ":raise_the_roof:"
    replace: "ƪ(˘⌣˘)ʃ"
  - trigger: ":dissatisfied:"
    replace: "(*￣m￣)"
  - trigger: ":studying:"
    replace: "___ψ(‥ )"
  - trigger: ":apology:"
    replace: "(シ_ _)シ"
  - trigger: ":lovestruck:"
    replace: "{♥‿♥}"
  - trigger: ":hello:"
    replace: "▼o･_･o▼"
  - trigger: ":owl:"
    replace: "ᕦ◉▿◉ᕤ"
  - trigger: ":phew:"
    replace: "ε-(´・｀) ﾌ"
  - trigger: ":wiping_tears:"
    replace: "（ つ Д ｀）"
  - trigger: ":waiter:"
    replace: "且_(ﾟ◇ﾟ；)ノﾞ"
  - trigger: ":mad:"
    replace: "o(>< )o⌒*"
  - trigger: ":dueling:"
    replace: "( `_)?(_' )"
  - trigger: ":piggy:"
    replace: ":©)"
  - trigger: ":sick:"
    replace: "[ ± _ ± ]"
  - trigger: ":smug:"
    replace: "( ˘︹˘ )"
  - trigger: ":dialing:"
    replace: "[]゛７(∀゜*）"
  - trigger: ":kiss:"
    replace: "(*^3^)/~☆"
  - trigger: ":clapping:"
    replace: "(￣ー￣)//””"
  - trigger: ":evil_laugh:"
    replace: "(๑≖ิิ益≖ิ๑)"
  - trigger: ":frog:"
    replace: ":(¦)"
  - trigger: ":girl:"
    replace: "(-_-)#"
  - trigger: ":scratching:"
    replace: "<(;￣ ･￣)"
  - trigger: ":discarding:"
    replace: "（´Д゜）/゜⌒。"
  - trigger: ":booing:"
    replace: "ヾ(｀ε´)ﾉ"
  - trigger: ":monkey:"
    replace: "@( o･ω･)@"
  - trigger: ":yawning:"
    replace: "(;´ρ`)"
  - trigger: ":playful:"
    replace: ":þ"
  - trigger: ":woody_allen:"
    replace: "ᡊ|◔じ◔|ᡊ "
  - trigger: ":up_in_arms:"
    replace: "{{|└(>o< )┘|}}"
  - trigger: ":applause:"
    replace: "(^^)//"
  - trigger: ":defeated:"
    replace: "(╯ნ_㇁ნ)╯"
  - trigger: ":tasty:"
    replace: "(๑╹ڡ╹๑)"
  - trigger: ":jamming_to_music:"
    replace: "♫.(◠౪◠).♫"
  - trigger: ":friendly:"
    replace: "(´∪`*)"
  - trigger: ":bummed_out:"
    replace: "(╯_╰)"
  - trigger: ":pompous:"
    replace: "(｡･ˇдˇ･｡)"
  - trigger: ":stinky:"
    replace: ":-{  -__-:"
  - trigger: ":banksy:"
    replace: "（　＾）／占~~~"
  - trigger: ":frightened:"
    replace: "(／。＼)"
